CREATE TABLE `ROLE` (
  `ID` INT (50) NOT NULL COMMENT 'ID' AUTO_INCREMENT,
  `CD` VARCHAR (255) NOT NULL COMMENT 'コード',
  `NAME` VARCHAR (255) NOT NULL COMMENT '名称',
  `REMARKS` VARCHAR (255) DEFAULT NULL COMMENT '備考',
  `DELETE_FLG` CHAR (1) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  `VERSION` INT (50) DEFAULT '0' COMMENT 'バージョン',
  `CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登録日時',
  `MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `MODIFIED_BY` VARCHAR (255) COMMENT '更新者',
  PRIMARY KEY(ID)
)
COMMENT='権限';
CREATE TABLE `STAFF_USER` (
  `ID` INT (50) NOT NULL COMMENT 'ID' AUTO_INCREMENT,
  `STAFF_USER_ID` VARCHAR (10) NOT NULL COMMENT '職員ID',
  `PASSWORD` VARCHAR (255) NOT NULL COMMENT 'パスワード',
  `NAME_KANA` VARCHAR (50) NOT NULL COMMENT '氏名カナ',
  `NAME` VARCHAR (25) NOT NULL COMMENT '氏名',
  `EMAIL` VARCHAR (255) NOT NULL COMMENT 'メールアドレス',
  `REMARKS` VARCHAR (255) DEFAULT NULL COMMENT '備考',
  `DELETE_FLG` CHAR (1) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  `VERSION` INT (50) DEFAULT '0' COMMENT 'バージョン',
  `CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登録日時',
  `MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `MODIFIED_BY` VARCHAR (255) COMMENT '更新者',
  PRIMARY KEY(ID,STAFF_USER_ID),
  UNIQUE KEY(STAFF_USER_ID)
)
COMMENT='職員';
CREATE TABLE `GENERAL_USER` (
  `ID` INT (50) NOT NULL COMMENT 'ID' AUTO_INCREMENT,
  `GENERAL_USER_ID` VARCHAR (10) NOT NULL COMMENT '利用者ID',
  `PASSWORD` VARCHAR (255) NOT NULL COMMENT 'パスワード',
  `NAME_KANA` VARCHAR (50) NOT NULL COMMENT 'フリガナ',
  `NAME` VARCHAR (25) NOT NULL COMMENT '氏名',
  `BIRTHDAY` DATE NOT NULL COMMENT '生年月日',
  `PHONE_NUMBER` VARCHAR (11) NOT NULL COMMENT '電話番号',
  `ADDRESS` VARCHAR (255) NOT NULL COMMENT '住所',
  `REMARKS` VARCHAR (255) DEFAULT NULL COMMENT '備考',
  `DELETE_FLG` CHAR (1) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  `VERSION` INT (50) DEFAULT '0' COMMENT 'バージョン',
  `CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登録日時',
  `MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `MODIFIED_BY` VARCHAR (255) COMMENT '更新者',
  PRIMARY KEY(ID,GENERAL_USER_ID),
  UNIQUE KEY(GENERAL_USER_ID)
)
COMMENT='一般利用者';
CREATE TABLE `GENRE` (
  `ID` INT (50) NOT NULL COMMENT 'ID' AUTO_INCREMENT,
  `GENRE_NAME` VARCHAR (25) COMMENT 'ジャンル名',
  `GENRE_CODE` VARCHAR (3) NOT NULL COMMENT 'ジャンルコード',
  `REMARKS` VARCHAR (255) DEFAULT NULL COMMENT '備考',
  `DELETE_FLG` CHAR (1) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  `VERSION` INT (50) DEFAULT '0' COMMENT 'バージョン',
  `CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登録日時',
  `MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `MODIFIED_BY` VARCHAR (255) COMMENT '更新者',
  PRIMARY KEY(ID,GENRE_CODE)
)
COMMENT='ジャンル';
CREATE TABLE `USER_ROLE_MAP` (
  `ID` INT (50) NOT NULL COMMENT 'ID' AUTO_INCREMENT,
  `STAFF_USER_ID` VARCHAR (10) COMMENT '職員ID',
  `GENERAL_USER_ID` VARCHAR (10) COMMENT '利用者ID',
  `ROLE_ID` INT (50) NOT NULL COMMENT '権限ID',
  `REMARKS` VARCHAR (255) DEFAULT NULL COMMENT '備考',
  `DELETE_FLG` CHAR (1) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  `VERSION` INT (50) DEFAULT '0' COMMENT 'バージョン',
  `CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登録日時',
  `MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `MODIFIED_BY` VARCHAR (255) COMMENT '更新者',
  PRIMARY KEY(ID),
  UNIQUE KEY(STAFF_USER_ID,GENERAL_USER_ID,ROLE_ID),
  FOREIGN KEY (STAFF_USER_ID) REFERENCES STAFF_USER(STAFF_USER_ID),
  FOREIGN KEY (GENERAL_USER_ID) REFERENCES GENERAL_USER(GENERAL_USER_ID),
  FOREIGN KEY (ROLE_ID) REFERENCES ROLE(ID)
)
COMMENT='ユーザー権限マップ';
CREATE TABLE `BOOK` (
  `ID` INT (50) NOT NULL COMMENT 'ID' AUTO_INCREMENT,
  `TITLE` VARCHAR (255) NOT NULL COMMENT 'タイトル',
  `AUTHOR` VARCHAR (50) NOT NULL COMMENT '著者',
  `ISBN_10` VARCHAR (10) COMMENT 'ISBN-10',
  `ISBN_13` VARCHAR (13) COMMENT 'ISBN-13',
  `PUBLISHER` VARCHAR (25) NOT NULL COMMENT '出版社',
  `GENRE_ID` INT (50) COMMENT 'ジャンルID',
  `SHELF_NUMBER` VARCHAR (3) COMMENT '棚番号',
  `CONTROL_NUMBER` VARCHAR (10) NOT NULL COMMENT '管理番号',
  `REMARKS` VARCHAR (255) DEFAULT NULL COMMENT '備考',
  `DELETE_FLG` CHAR (1) NOT NULL DEFAULT '0' COMMENT '削除フラグ',
  `VERSION` INT (50) DEFAULT '0' COMMENT 'バージョン',
  `CREATED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '登録日時',
  `MODIFIED` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新日時',
  `MODIFIED_BY` VARCHAR (255) COMMENT '更新者',
  PRIMARY KEY(ID,CONTROL_NUMBER),
  FOREIGN KEY (GENRE_ID) REFERENCES GENRE(ID)
)
COMMENT='図書';